service: sls-data-pipelines

package:
  individually: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - serverless-pseudo-parameters


custom:
  firehoseS3Prefix: 'destination/'
  firehoseCompressionFormat: UNCOMPRESSED


provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  profile: cloudway-nick
  reservedConcurrency: 1

functions:
  RetrieveXMLTrafficData:
    handler: handler.handle
    module: src/RetrieveXMLTrafficData
    environment:
      TRAFFIC_DATA_URL: "http://miv.opendata.belfla.be/miv/verkeersdata"
      BUCKET_NAME:
        Ref: OriginBucket
      S3_XML_PREFIX: "xml/input/"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:PutObject
        Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "OriginBucket"
              - "/*"
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: false

  TransformTrafficToJsonData:
    handler: handler.handle
    module: src/TransformTrafficDataToJson
    environment:
      BUCKET_NAME:
        Ref: OriginBucket
      S3_XML_PREFIX: "xml/input/"
      S3_JSON_PREFIX: "json/input/"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "OriginBucket"
              - "/*"
    events:
      - s3:
          bucket:
            Ref: OriginBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: xml/input/
            - suffix: .xml
          existing: true

  PublishTrafficData:
    handler: handler.handle
    module: src/PublishTrafficData
    memorySize: 3008
    timeout: 60
    environment:
      BUCKET_NAME:
        Ref: OriginBucket
      S3_JSON_PREFIX: "json/input/"
      DELIVERY_STREAM_NAME:
        Ref: DeliveryStream
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:GetObject
        Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "OriginBucket"
              - "/*"
      - Effect: "Allow"
        Action:
          - "firehose:PutRecord"
          - "firehose:PutRecordBatch"
        Resource: { Fn::GetAtt: [ DeliveryStream, Arn ] }
    events:
      - s3:
          bucket:
            Ref: OriginBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: json/input/
            - suffix: .json
          existing: true

resources:
  - ${file(resources/firehose.yml)}
  - Resources:
      OriginBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: traffic-data-origin-bucket
      DeliveryBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: traffic-data-destination-bucket
  #  Outputs:
  #     NewOutput:
  #       Description: "Description for the output"
  #       Value: "Some output value"
