service: sls-data-pipelines

package:
  individually: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - serverless-pseudo-parameters


custom:
  firehoseS3Prefix: 'destination/'
  firehoseS3AnylticsResultsPrefix: 'analytics/results/'
  firehoseCompressionFormat: UNCOMPRESSED
  stage: "${opt:stage, self:provider.stage}"


provider:
  name: aws
  stage: dev
  runtime: python3.7
  region: eu-west-1
  reservedConcurrency: 1
  memorySize: 512
  versionFunctions: false
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: '*'
  environment:
    thundra_apiKey: ${ssm:/thundra/apiKey}
    thundra_agent_lambda_handler: handler.handle

functions:
  RetrieveXMLTrafficData:
    handler: thundra.handler.wrapper
    module: src/RetrieveXMLTrafficData
    layers:
      - arn:aws:lambda:eu-west-1:269863060030:layer:thundra-lambda-python-layer:33
    environment:
      TRAFFIC_DATA_URL: "http://miv.opendata.belfla.be/miv/verkeersdata"
      BUCKET_NAME:
        Ref: OriginBucket
      S3_XML_PREFIX: "xml/input/"
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:PutObject
        Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "OriginBucket"
              - "/*"
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: false

  TransformTrafficToJsonData:
    handler: thundra.handler.wrapper
    module: src/TransformTrafficDataToJson
    layers:
      - arn:aws:lambda:eu-west-1:269863060030:layer:thundra-lambda-python-layer:33
    environment:
      BUCKET_NAME:
        Ref: OriginBucket
      S3_XML_PREFIX: "xml/input/"
      S3_JSON_PREFIX: "json/input/"
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "OriginBucket"
              - "/*"
    events:
      - s3:
          bucket:
            Ref: OriginBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: xml/input/
            - suffix: .xml
          existing: true

  PublishTrafficDataFunction:
    handler: thundra.handler.wrapper
    module: src/PublishTrafficData
    layers:
      - arn:aws:lambda:eu-west-1:269863060030:layer:thundra-lambda-python-layer:33
    environment:
      BUCKET_NAME:
        Ref: OriginBucket
      S3_JSON_PREFIX: "json/input/"
      DELIVERY_STREAM_NAME:
        Ref: DeliveryStream
      thundra_agent_lambda_debug_enable: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:GetObject
        Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "OriginBucket"
              - "/*"
      - Effect: "Allow"
        Action:
          - "firehose:PutRecord"
          - "firehose:PutRecordBatch"
        Resource: { Fn::GetAtt: [ DeliveryStream, Arn ] }
    events:
      - s3:
          bucket:
            Ref: OriginBucket
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: json/input/
            - suffix: .json

  StreamProcessor:
    handler: thundra.handler.wrapper
    module: src/StreamProcessor
    timeout: 300
    environment:
      FILTER_IDS: '1897, 957, 3159, 3977, 1065, 569'
      thundra_agent_lambda_debug_enable: true
    layers:
        - arn:aws:lambda:eu-west-1:269863060030:layer:thundra-lambda-python-layer:33
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "firehose:PutRecord"
          - "firehose:PutRecordBatch"
        Resource: !GetAtt DeliveryStream.Arn

  TrafficAlertsFunction:
    handler: thundra.handler.wrapper
    module: src/TrafficAlertsFunction
    timeout: 10
    reservedConcurrency: 0
    environment:
      REGION: eu-west-1
    layers:
      - arn:aws:lambda:eu-west-1:269863060030:layer:thundra-lambda-python-layer:33
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "kinesis:DescribeStream"
          - "kinesis:GetShardIterator"
          - "kinesis:GetRecords"
        Resource: !GetAtt DestinationStream.Arn
      - Effect: "Allow"
        Action:
          - "kinesis:DescribeStream"
          - "kinesis:GetShardIterator"
          - "kinesis:GetRecords"
        Resource: !GetAtt DestinationStream.Arn
      - Effect: "Allow"
        Action:
          - "sqs:SendMessage"
          - "sqs:ListQueues"
        Resource: !GetAtt TrafficAlertsDeadQueue.Arn
    events:
      - stream:
          type: kinesis
          arn: !GetAtt DestinationStream.Arn
          batchSize: 10
          batchWindow: 30
          maximumRetryAttempts: 2
          startingPosition: LATEST
          enabled: true
          destinations:
            onFailure:
              arn: !GetAtt TrafficAlertsDeadQueue.Arn
              type: sqs

  SaveAnalyticsResults:
    handler: thundra.handler.wrapper
    module: src/SaveAnalyticsResults
    timeout: 10
    reservedConcurrency: 1
    layers:
      - arn:aws:lambda:eu-west-1:269863060030:layer:thundra-lambda-python-layer:33
    environment:
      TABLE_NAME: !Ref AnalyticsResultsTable
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "kinesis:DescribeStream"
          - "kinesis:GetShardIterator"
          - "kinesis:GetRecords"
        Resource: !GetAtt DestinationStream.Arn
      - Effect: "Allow"
        Action:
          - "dynamodb:DescribeStream"
          - "dynamodb:DescribeTable"
          - "dynamodb:BatchWrite*"
          - "dynamodb:Delete*"
          - "dynamodb:Update*"
          - "dynamodb:PutItem"
        Resource: !GetAtt AnalyticsResultsTable.Arn
      - Effect: "Allow"
        Action:
          - "sqs:SendMessage"
          - "sqs:ListQueues"
        Resource: !GetAtt SaveAnalyticsDeadQueue.Arn
    events:
      - stream:
          type: kinesis
          arn: !GetAtt DestinationStream.Arn
          batchSize: 10
          batchWindow: 30
          maximumRetryAttempts: 2
          startingPosition: LATEST
          enabled: true
          destinations:
            onFailure:
              arn: !GetAtt SaveAnalyticsDeadQueue.Arn
              type: sqs


resources:
  - ${file(resources/firehose.yml)}
  - ${file(resources/kinesis.yml)}
  - ${file(resources/sqs.yml)}
  - ${file(resources/s3.yml)}
  - ${file(resources/dynamodb.yml)}

  - Outputs:
      DeliveryStreamName:
        Description: "Name of the firehose over which all traffic events flow"
        Value: !Ref DeliveryStream
      DynamoDBAnalyticsResultTableName:
        Description: "Single table that holds the analytics results"
        Value: !Ref AnalyticsResultsTable
