Resources:
  RealTimeAnalyticsPerPointTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "uniqueId"
          AttributeType: "S"
        - AttributeName: "outputType"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "uniqueId"
          KeyType: "HASH"
        - AttributeName: "outputType"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  TrafficJamAlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "uniqueId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "uniqueId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES