Resources:
  DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - DeliveryStreamRole
    Properties:
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        Prefix: ${self:custom.firehoseS3Prefix}
        BucketARN:
          'Fn::GetAtt': [DeliveryBucket, Arn]
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        CompressionFormat: ${self:custom.firehoseCompressionFormat}
        RoleARN:
          'Fn::GetAtt': [DeliveryStreamRole, Arn]
#        ProcessingConfiguration:
#          Enabled: true
#          Processors:
#            - Type: Lambda
#              Parameters:
#                - ParameterName: LambdaArn
#                  ParameterValue:
#                    Fn:GetAtt StreamProcessFunction.Arn

  DeliveryStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: [ firehose.amazonaws.com ] }
            Action: [ sts:AssumeRole ]
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - 's3:AbortMultipartUpload'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:ListBucket'
                - 's3:ListBucketMultipartUploads'
                - 's3:PutObject'
              Resource:
                - { Fn::GetAtt: [ DeliveryBucket, Arn ] }
                - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref DeliveryBucket
                    - '*'





#              - Effect: Allow
#                Action: 's3:*'
#                Resource: { Fn::GetAtt: [ DeliveryBucket, Arn ] }
#  DeliveryStreamPolicy:
#    Type: AWS::IAM::Policy
#    Properties:
#      Roles:
#        - Ref DeliveryStreamRole
#      PolicyName: firehose_delivery_policy
#      PolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Effect: Allow
#            Action: '*'
#              - 's3:AbortMultipartUpload'
#              - 's3:GetBucketLocation'
#              - 's3:GetObject'
#              - 's3:ListBucket'
#              - 's3:ListBucketMultipartUploads'
#              - 's3:PutObject'
#            Resource: '*'
#              - { Fn::GetAtt: [ DeliveryBucket, Arn ] }
#              - Fn::Join:
#                - ''
#                - - 'arn:aws:s3:::'
#                  - Ref DeliveryBucket
#                  - '*'
