Resources:
  OriginBucket:
    Type: AWS::S3::Bucket
  DeliveryBucket:
    Type: AWS::S3::Bucket
  AnalyticsBucket:
    Type: AWS::S3::Bucket
  AthenaQueryResultsBucket:
    Type: AWS::S3::Bucket
  ResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled