Resources:
  SaveAnalyticsDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 5
      MessageRetentionPeriod: 86400 # 1 Day
      QueueName: ${self:service.name}-${self:provider.stage}-process-analytics-dead-queue
  PowerBiForwarderDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 5
      MessageRetentionPeriod: 86400 # 1 Day
  TrafficAlertsDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 5
      MessageRetentionPeriod: 86400 # 1 Day
      QueueName: ${self:service.name}-${self:provider.stage}-traffic-alerts-dead-queue